name: games_pro
description: A gaming tournament platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  google_sign_in: ^6.1.6
  flutter_riverpod: ^2.4.9
  go_router: ^15.1.1
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  intl: ^0.20.2
  uuid: ^4.3.3
  share_plus: ^11.0.0
  url_launcher: ^6.2.4
  youtube_player_flutter: ^9.1.0
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  logger: ^2.0.2+1
  firebase_auth_web: ^5.0.0
  google_sign_in_web: ^0.12.4+4
  firebase_messaging_web: ^3.3.0
  firebase_storage_web: ^3.3.0
  cloud_firestore_web: ^4.4.7
  google_fonts: ^6.1.0
  http: ^1.2.1
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^3.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/ 